Update requirements.txt
Previous error persists... same same but different.... part 2 of hopefully 2
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-d2d29be66561> in <module>
----> 1 from fastai.vision.all import *
      2 from fastai.vision.widgets import *

~/.heroku/python/lib/python3.6/site-packages/fastai/vision/all.py in <module>
----> 1 from ..basics import *
      2 from ..callback.all import *
      3 from .augment import *
      4 from .core import *
      5 from .data import *

~/.heroku/python/lib/python3.6/site-packages/fastai/basics.py in <module>
----> 1 from .data.all import *
      2 from .optimizer import *
      3 from .callback.core import *
      4 from .learner import *
      5 from .metrics import *

~/.heroku/python/lib/python3.6/site-packages/fastai/data/all.py in <module>
      3 from .load import *
      4 from .external import *
----> 5 from .transforms import *
      6 from .block import *

~/.heroku/python/lib/python3.6/site-packages/fastai/data/transforms.py in <module>
    228 
    229 # Cell
--> 230 class Categorize(DisplayedTransform):
    231     "Reversible transform of category string to `vocab` id"
    232     loss_func,order,store_attrs=CrossEntropyLossFlat(),1,'vocab,add_na'

~/.heroku/python/lib/python3.6/site-packages/fastai/data/transforms.py in Categorize()
    230 class Categorize(DisplayedTransform):
    231     "Reversible transform of category string to `vocab` id"
--> 232     loss_func,order,store_attrs=CrossEntropyLossFlat(),1,'vocab,add_na'
    233     def __init__(self, vocab=None, sort=True, add_na=False):
    234         store_attr(self, self.store_attrs+',sort')

~/.heroku/python/lib/python3.6/site-packages/fastcore/utils.py in _f(*args, **kwargs)
    470         init_args.update(log)
    471         setattr(inst, 'init_args', init_args)
--> 472         return inst if to_return else f(*args, **kwargs)
    473     return _f
    474 

~/.heroku/python/lib/python3.6/site-packages/fastai/layers.py in __init__(self, axis, *args, **kwargs)
    304     y_int = True
    305     @use_kwargs_dict(keep=True, weight=None, ignore_index=-100, reduction='mean')
--> 306     def __init__(self, *args, axis=-1, **kwargs): super().__init__(nn.CrossEntropyLoss, *args, axis=axis, **kwargs)
    307     def decodes(self, x):    return x.argmax(dim=self.axis)
    308     def activation(self, x): return F.softmax(x, dim=self.axis)

~/.heroku/python/lib/python3.6/site-packages/fastcore/utils.py in _f(*args, **kwargs)
    470         init_args.update(log)
    471         setattr(inst, 'init_args', init_args)
--> 472         return inst if to_return else f(*args, **kwargs)
    473     return _f
    474 

~/.heroku/python/lib/python3.6/site-packages/fastai/layers.py in __init__(self, loss_cls, axis, flatten, floatify, is_2d, *args, **kwargs)
    279     activation=decodes=noops
    280     def __init__(self, loss_cls, *args, axis=-1, flatten=True, floatify=False, is_2d=True, **kwargs):
--> 281         store_attr(self, "axis,flatten,floatify,is_2d")
    282         self.func = loss_cls(*args,**kwargs)
    283         functools.update_wrapper(self, self.func)

~/.heroku/python/lib/python3.6/site-packages/fastcore/utils.py in store_attr(names, self, but, **attrs)
     95     args,varargs,keyw,locs = inspect.getargvalues(fr)
     96     if self is None: self = locs[args[0]]
---> 97     if not hasattr(self, '__stored_args__'): self.__stored_args__ = {}
     98     if attrs: return _store_attr(self, **attrs)
     99 

AttributeError: 'str' object has no attribute '__stored_args__'